/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.edu.espe.physiomatic.view;

import com.google.gson.Gson;
import ec.edu.espe.filemanager.utils.FileManager;
import ec.edu.espe.physiomatic.model.Physioterapist;
import javax.swing.JOptionPane;

/**
 *
 * @author Acer
 * @author Yulliana Roman ESPE-DCCO
 */
public class FrmRegistrationPhysioterapist extends javax.swing.JFrame {

    /**
     * Creates new form JFRegistrationPhysioterapist
     */
    public FrmRegistrationPhysioterapist() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbTitle = new javax.swing.JLabel();
        lbName = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        lbLastName = new javax.swing.JLabel();
        txtLastName = new javax.swing.JTextField();
        lbUserName = new javax.swing.JLabel();
        txtUser = new javax.swing.JTextField();
        lbPassword = new javax.swing.JLabel();
        pwdConfirmPassword = new javax.swing.JPasswordField();
        lbConfirmPassword = new javax.swing.JLabel();
        pwdPassword = new javax.swing.JPasswordField();
        btnNext = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        lbId = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        lbEmail = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        lbAddress = new javax.swing.JLabel();
        txtAddress = new javax.swing.JTextField();
        lbPhoneNumber = new javax.swing.JLabel();
        txtPhoneNumber = new javax.swing.JTextField();
        lbBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbTitle.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        lbTitle.setForeground(new java.awt.Color(255, 255, 255));
        lbTitle.setText("Registrar Fisioterapeuta");
        getContentPane().add(lbTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, 630, 50));

        lbName.setBackground(new java.awt.Color(255, 255, 255));
        lbName.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        lbName.setForeground(new java.awt.Color(255, 255, 255));
        lbName.setText("Nombre:");
        getContentPane().add(lbName, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, 150, 30));

        txtName.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtName.setForeground(new java.awt.Color(0, 51, 51));
        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });
        getContentPane().add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 140, 500, 30));

        lbLastName.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        lbLastName.setForeground(new java.awt.Color(255, 255, 255));
        lbLastName.setText("Apellido:");
        getContentPane().add(lbLastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, 150, 30));

        txtLastName.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtLastName.setForeground(new java.awt.Color(0, 51, 51));
        txtLastName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLastNameActionPerformed(evt);
            }
        });
        getContentPane().add(txtLastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 180, 500, 30));

        lbUserName.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        lbUserName.setForeground(new java.awt.Color(255, 255, 255));
        lbUserName.setText("Usuario:");
        getContentPane().add(lbUserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 340, -1, -1));

        txtUser.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtUser.setForeground(new java.awt.Color(0, 51, 51));
        txtUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUserActionPerformed(evt);
            }
        });
        getContentPane().add(txtUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 340, 500, 30));

        lbPassword.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        lbPassword.setForeground(new java.awt.Color(255, 255, 255));
        lbPassword.setText("Contraseña:");
        getContentPane().add(lbPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 380, -1, -1));

        pwdConfirmPassword.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        pwdConfirmPassword.setForeground(new java.awt.Color(0, 51, 51));
        getContentPane().add(pwdConfirmPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 420, 350, 30));

        lbConfirmPassword.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        lbConfirmPassword.setForeground(new java.awt.Color(255, 255, 255));
        lbConfirmPassword.setText("Confirmar contraseña:");
        getContentPane().add(lbConfirmPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 420, -1, 30));

        pwdPassword.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        pwdPassword.setForeground(new java.awt.Color(0, 51, 51));
        pwdPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pwdPasswordActionPerformed(evt);
            }
        });
        getContentPane().add(pwdPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 380, 460, 30));

        btnNext.setBackground(new java.awt.Color(0, 51, 51));
        btnNext.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnNext.setForeground(new java.awt.Color(255, 255, 255));
        btnNext.setText("Guardar");
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });
        getContentPane().add(btnNext, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 480, 110, 40));

        btnBack.setBackground(new java.awt.Color(0, 51, 51));
        btnBack.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnBack.setForeground(new java.awt.Color(255, 255, 255));
        btnBack.setText("Cancelar");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        getContentPane().add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 480, 110, 40));

        lbId.setBackground(new java.awt.Color(0, 51, 51));
        lbId.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        lbId.setForeground(new java.awt.Color(255, 255, 255));
        lbId.setText("C.I:");
        getContentPane().add(lbId, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, -1, -1));

        txtId.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtId.setForeground(new java.awt.Color(0, 51, 51));
        getContentPane().add(txtId, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 100, 550, 30));

        lbEmail.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        lbEmail.setForeground(new java.awt.Color(255, 255, 255));
        lbEmail.setText("Email:");
        getContentPane().add(lbEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 260, -1, -1));

        txtEmail.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtEmail.setForeground(new java.awt.Color(0, 51, 51));
        txtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailActionPerformed(evt);
            }
        });
        getContentPane().add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 260, 520, 30));

        lbAddress.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        lbAddress.setForeground(new java.awt.Color(255, 255, 255));
        lbAddress.setText("Dirección:");
        getContentPane().add(lbAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 300, -1, -1));

        txtAddress.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtAddress.setForeground(new java.awt.Color(0, 51, 51));
        getContentPane().add(txtAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 300, 480, 30));

        lbPhoneNumber.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        lbPhoneNumber.setForeground(new java.awt.Color(255, 255, 255));
        lbPhoneNumber.setText("Número de teléfono:");
        getContentPane().add(lbPhoneNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, -1, -1));

        txtPhoneNumber.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtPhoneNumber.setForeground(new java.awt.Color(0, 51, 51));
        getContentPane().add(txtPhoneNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 220, 370, 30));

        lbBackground.setBackground(new java.awt.Color(0, 102, 102));
        lbBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/edu/espe/pictures/background2.jpg"))); // NOI18N
        lbBackground.setText("jLabel7");
        getContentPane().add(lbBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 750, 560));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtLastNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLastNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLastNameActionPerformed

    private void pwdPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pwdPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pwdPasswordActionPerformed

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameActionPerformed

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
        String dataToSave = "Desea guardar esta información?\n" + txtName.getText() + "\n" + txtLastName.getText() + "\n" + txtUser.getText() + "\n" + pwdPassword.getText();
        int selection = JOptionPane.showConfirmDialog(null, dataToSave, "Registro de Fisioterapista", JOptionPane.YES_NO_CANCEL_OPTION);
        if (selection == 0) {
            JOptionPane.showConfirmDialog(null, "Se guardó la información", "Registro de Fisioterapista" + "\nGuardado", JOptionPane.INFORMATION_MESSAGE);
            register();
            emptyFields();            
        }
        if (selection == 1) {
            JOptionPane.showConfirmDialog(null, "NO Se guardó la información", "Registro de Fisioterapista", JOptionPane.ERROR_MESSAGE);

        }
        if (selection == 2) {
            JOptionPane.showConfirmDialog(null, "La acción fue cancelada", "Registro de Fisioterapista", JOptionPane.WARNING_MESSAGE);
            emptyFields();
        }
    }//GEN-LAST:event_btnNextActionPerformed

    private void txtUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUserActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        changeVisibility();
    }//GEN-LAST:event_btnBackActionPerformed

    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailActionPerformed

    public void changeVisibility() {
        FrmPhysioterapistManagment frmPhysiomaticMagament = new FrmPhysioterapistManagment();
        this.setVisible(false);
        frmPhysiomaticMagament.setVisible(true);
    }

    public void emptyFields() {
        txtLastName.setText("");
        txtName.setText("");
        txtUser.setText("");
        pwdPassword.setText("");
        pwdConfirmPassword.setText("");
        txtAddress.setText("");
        txtEmail.setText("");
        txtPhoneNumber.setText("");
    }

    public void register() {
        Gson gson = new Gson();
        FileManager.save("physioterapist.json", gson.toJson(create()));
    }    

    public Physioterapist create() {
        String name=txtName.getText();
        String lastName=txtLastName.getText();
        String userName=txtUser.getText();
        String password=pwdConfirmPassword.getText();
        String phoneNumber = txtPhoneNumber.getText();
        String email= txtEmail.getText();
        String address=txtAddress.getText();
        long id = Long.parseLong(txtId.getText());
        Physioterapist physiotherapist = new Physioterapist(userName, password, id, address, name, lastName, email, phoneNumber);
        return physiotherapist;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmRegistrationPhysioterapist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmRegistrationPhysioterapist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmRegistrationPhysioterapist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmRegistrationPhysioterapist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmRegistrationPhysioterapist().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnNext;
    private javax.swing.JLabel lbAddress;
    private javax.swing.JLabel lbBackground;
    private javax.swing.JLabel lbConfirmPassword;
    private javax.swing.JLabel lbEmail;
    private javax.swing.JLabel lbId;
    private javax.swing.JLabel lbLastName;
    private javax.swing.JLabel lbName;
    private javax.swing.JLabel lbPassword;
    private javax.swing.JLabel lbPhoneNumber;
    private javax.swing.JLabel lbTitle;
    private javax.swing.JLabel lbUserName;
    private javax.swing.JPasswordField pwdConfirmPassword;
    private javax.swing.JPasswordField pwdPassword;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtLastName;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPhoneNumber;
    private javax.swing.JTextField txtUser;
    // End of variables declaration//GEN-END:variables
}
