/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.edu.espe.physiomatic.view;

/**
 *
 * @author Yulliana Roman ESPE-DCCO
 */
public class FrmMenuPhysioterapist extends javax.swing.JFrame {

    /**
     * Creates new form FrmMenuPhysioterapist
     */
    public FrmMenuPhysioterapist() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu4 = new javax.swing.JMenu();
        lbTittle = new javax.swing.JLabel();
        lbName = new javax.swing.JLabel();
        btnExit = new javax.swing.JButton();
        btnBack = new javax.swing.JToggleButton();
        lbBackground = new javax.swing.JLabel();
        mbrPhysioterapistMenu = new javax.swing.JMenuBar();
        mnuPatient = new javax.swing.JMenu();
        mitmShow = new javax.swing.JMenuItem();
        mnuAppointment = new javax.swing.JMenu();
        mitmAddAppoinment = new javax.swing.JMenuItem();
        mitmShowAppoinment = new javax.swing.JMenuItem();
        mnuClinicalHistory = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        mitmShowClinicalHistory = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();

        jMenu4.setText("jMenu4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbTittle.setFont(new java.awt.Font("Arial", 3, 60)); // NOI18N
        lbTittle.setForeground(new java.awt.Color(254, 254, 254));
        lbTittle.setText("PHYSIOMATIC v1.0");
        getContentPane().add(lbTittle, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 680, 70));

        lbName.setFont(new java.awt.Font("Arial", 2, 25)); // NOI18N
        lbName.setForeground(new java.awt.Color(255, 255, 255));
        lbName.setText("Powered By SDC Team");
        getContentPane().add(lbName, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, -1, -1));

        btnExit.setBackground(new java.awt.Color(0, 51, 51));
        btnExit.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnExit.setForeground(new java.awt.Color(255, 255, 255));
        btnExit.setText("Salir");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        getContentPane().add(btnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 420, 80, -1));

        btnBack.setBackground(new java.awt.Color(0, 51, 51));
        btnBack.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnBack.setForeground(new java.awt.Color(255, 255, 255));
        btnBack.setText("Atrás");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        getContentPane().add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 420, 80, -1));

        lbBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/edu/espe/pictures/background.jpg"))); // NOI18N
        lbBackground.setText("jLabel1");
        getContentPane().add(lbBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 729, 565));

        mnuPatient.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N
        mnuPatient.setText("Pacientes");

        mitmShow.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        mitmShow.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        mitmShow.setForeground(new java.awt.Color(0, 51, 51));
        mitmShow.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/edu/espe/pictures/mostrar.png"))); // NOI18N
        mitmShow.setText("Mostrar");
        mitmShow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitmShowActionPerformed(evt);
            }
        });
        mnuPatient.add(mitmShow);

        mbrPhysioterapistMenu.add(mnuPatient);

        mnuAppointment.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18))); // NOI18N
        mnuAppointment.setText("Citas");

        mitmAddAppoinment.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        mitmAddAppoinment.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        mitmAddAppoinment.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/edu/espe/pictures/appointmentIcon.png"))); // NOI18N
        mitmAddAppoinment.setText("Generar");
        mitmAddAppoinment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitmAddAppoinmentActionPerformed(evt);
            }
        });
        mnuAppointment.add(mitmAddAppoinment);

        mitmShowAppoinment.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.CTRL_MASK));
        mitmShowAppoinment.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        mitmShowAppoinment.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/edu/espe/pictures/mostrar.png"))); // NOI18N
        mitmShowAppoinment.setText("Mostrar");
        mitmShowAppoinment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitmShowAppoinmentActionPerformed(evt);
            }
        });
        mnuAppointment.add(mitmShowAppoinment);

        mbrPhysioterapistMenu.add(mnuAppointment);

        mnuClinicalHistory.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18))); // NOI18N
        mnuClinicalHistory.setText("Historiales Médicos");
        mnuClinicalHistory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuClinicalHistoryActionPerformed(evt);
            }
        });

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_G, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/edu/espe/pictures/ClinicalHistoryIcon_1.png"))); // NOI18N
        jMenuItem1.setText("Generar");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        mnuClinicalHistory.add(jMenuItem1);

        mitmShowClinicalHistory.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.SHIFT_MASK));
        mitmShowClinicalHistory.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        mitmShowClinicalHistory.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/edu/espe/pictures/mostrar.png"))); // NOI18N
        mitmShowClinicalHistory.setText("Mostrar");
        mitmShowClinicalHistory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitmShowClinicalHistoryActionPerformed(evt);
            }
        });
        mnuClinicalHistory.add(mitmShowClinicalHistory);

        jMenuItem3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jMenuItem3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/edu/espe/pictures/searchIcon.png"))); // NOI18N
        jMenuItem3.setText("Buscar");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        mnuClinicalHistory.add(jMenuItem3);

        jMenuItem2.setText("Añadir diagnóstico");
        mnuClinicalHistory.add(jMenuItem2);

        mbrPhysioterapistMenu.add(mnuClinicalHistory);

        setJMenuBar(mbrPhysioterapistMenu);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mitmShowAppoinmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitmShowAppoinmentActionPerformed
        FrmAppointmentDisplay frmAppointmentDisplay = new FrmAppointmentDisplay();
        this.setVisible(false);
        frmAppointmentDisplay.setVisible(true);
    }//GEN-LAST:event_mitmShowAppoinmentActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        FrmLogin frmLogin = new FrmLogin();
        this.setVisible(false);
        frmLogin.setVisible(true);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnExitActionPerformed

    private void mitmShowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitmShowActionPerformed
        FrmPatientTable frmTable =  new FrmPatientTable();
        this.setVisible(false);
        frmTable.setVisible(true);
    }//GEN-LAST:event_mitmShowActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        FrmCreateClinicalHistory frmCreateClinicalHistory = new FrmCreateClinicalHistory();
        this.setVisible(false);
        frmCreateClinicalHistory.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void mitmShowClinicalHistoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitmShowClinicalHistoryActionPerformed
        FrmClinicalHistoryTable frmClinicalHistoryDisplay = new FrmClinicalHistoryTable();
        this.setVisible(false);
        frmClinicalHistoryDisplay.setVisible(true);
    }//GEN-LAST:event_mitmShowClinicalHistoryActionPerformed

    private void mitmAddAppoinmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitmAddAppoinmentActionPerformed
        FrmAppointmentScheduling frmAppointmentScheduling = new FrmAppointmentScheduling();
        this.setVisible(false);
        frmAppointmentScheduling.setVisible(true);
    }//GEN-LAST:event_mitmAddAppoinmentActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        FrmClinicalHistoryDisplay frmClinicalHistoryDisplay = new FrmClinicalHistoryDisplay();
        this.setVisible(false);
        frmClinicalHistoryDisplay.setVisible(true);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void mnuClinicalHistoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuClinicalHistoryActionPerformed
        FrmCreateDiagnostic frmCreateDiagnostic = new FrmCreateDiagnostic();
        this.setVisible(false);
        frmCreateDiagnostic.setVisible(true);
    }//GEN-LAST:event_mnuClinicalHistoryActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmMenuPhysioterapist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmMenuPhysioterapist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmMenuPhysioterapist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmMenuPhysioterapist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmMenuPhysioterapist().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnBack;
    private javax.swing.JButton btnExit;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JLabel lbBackground;
    private javax.swing.JLabel lbName;
    private javax.swing.JLabel lbTittle;
    private javax.swing.JMenuBar mbrPhysioterapistMenu;
    private javax.swing.JMenuItem mitmAddAppoinment;
    private javax.swing.JMenuItem mitmShow;
    private javax.swing.JMenuItem mitmShowAppoinment;
    private javax.swing.JMenuItem mitmShowClinicalHistory;
    private javax.swing.JMenu mnuAppointment;
    private javax.swing.JMenu mnuClinicalHistory;
    private javax.swing.JMenu mnuPatient;
    // End of variables declaration//GEN-END:variables
}
